### ISSUE TITLE
Problems when using clickfix under Windows 10

### ISSUE THREAD

**Issue by JDJADU** [CemraJC/clickfix#10]
After activating fix for the left button, some windows become unselectable or unswitchable, Just open FireFox and than RegEdit and try to select FF and then RegEdit and then FF again. Or try to hide RegEdit by clicking its icon in the main panel. The solution is to make a rightclick and then leftclick. The problem is only with some system apps. When they are activated everything goes wrong. After closing them everything is working back again.

**Comment by D-Niermann** [comment]
Bump. I have the same Problem.

**Comment by JDJADU** [comment]
Hello


Try to run ClickFIx as administrator.

 
Jan Dudek


Od: "D-Niermann" notifications@github.com
Komu: "CemraJC/clickfix" clickfix@noreply.github.com
Kopie: "JDJADU" dudek@jadu.cz,"Author" author@noreply.github.com
Datum: Thu, 02 Apr 2020 06:20:48 -0700
Předmet: Re: [CemraJC/clickfix] Problems when using clickfix under Windows 10 (#10)



Bump. I have the same Problem.

**Comment by Gaabe** [comment]
> Hello Try to run ClickFIx as administrator.   Jan Dudek Od: "D-Niermann" notifications@github.com Komu: "CemraJC/clickfix" clickfix@noreply.github.com Kopie: "JDJADU" dudek@jadu.cz,"Author" author@noreply.github.com Datum: Thu, 02 Apr 2020 06:20:48 -0700 Předmet: Re: [CemraJC/clickfix] Problems when using clickfix under Windows 10 (#10) Bump. I have the same Problem. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Came here with the same issue, and can confirm that running it as an administrator solves it, thanks!
