### ISSUE TITLE
Is there a non-keyboard way to toggle active/disabled?

### ISSUE THREAD

**Issue by POTSandSTOP** [CemraJC/clickfix#12]
If there isn't, can you add a way? For example, a new option to the ClickFix icon in the system tray? And maybe in Full Settings have a checkbox for Enable that would also be used by "Start on Windows Startup"?

**Comment by CemraJC** [comment]
Hello! 
No less than 2 years later, I have finally added a menu item to toggle the active/disabled functionality. 
Sorry for the delay, with any luck you've found yourself a new mouse by now anyway.
