### ISSUE TITLE
Back pressure and forward pressure settings are flipped

### ISSUE THREAD

**Issue by ovidiupruteanu** [CemraJC/clickfix#14]
https://github.com/CemraJC/clickfix/blob/65a9fc891f031d7ef6744cdfdfce6ec0e82132ff/ClickFix.ahk#L25-L26

**Comment by CemraJC** [comment]
Good call! If I update this now, it may mess with people's existing configs unfortunately - closing for now, if I ever need to do a major upgrade, I'll keep this in mind
