### ISSUE TITLE
Avast Premium Security

### ISSUE THREAD

**Issue by denis13041973** [CemraJC/clickfix#19]
Hello!

Avast Premium Security doesn't allow clicking any of its notifications if clickfix is running. 
After you disable clickfix, Avast behaves normally. 
Can this be fixed?

Thanks

**Comment by CemraJC** [comment]
Hello! I've had a look at this, and Avast is using a strange overlay technology for "security" reasons (specifically to stop malicious programs from closing the notifications).

Unfortunately, fixing this is a bit above my paygrade - best I can think of is to try and add an AntiVirus exception for ClickFix.exe, but I somehow doubt that will work.

Sorry I couldn't be of more help

**Comment by Neurotoxin001** [comment]
https://www.virustotal.com/gui/file/91915970ec2b97673a351f52628d404b505ced5bab449c67d85c9745f5f04c7d - version 3
https://www.virustotal.com/gui/file/a4da2a5698aee140a8f96fe3b00efaf64ace10e45a04278e2606ff824a366873 - version 2.6.1
