### ISSUE TITLE
ClickFix won't start with Windows 10 as Administrator

### ISSUE THREAD

**Issue by TheSalx1995** [CemraJC/clickfix#20]
Am I missing something?

I just toggled the option Start on Windows Startup. No problems at first, but I got the problem in which I can't click certain areas, which is solved by setting the program to run as administrator. The problem is that because of this, ClickFix won't start on startup and I have to execute it manually.

**Comment by e3rerr44** [comment]
answer is run without admin privilegios

**Comment by TheSalx1995** [comment]
> answer is run without admin privilegios

I don't think you properly read my post. Running without admin privilege makes the program cause some issues in which you cannot click certain areas. In fact, it can go as bad as having to resort to keyboard combinations to get rid of it.

Hence, removing admin privileges is not a solution, unless devs solve that problem in the first place.

**Comment by CemraJC** [comment]
Hello! Sorry for the delay: administrator rights are a tricky thing to deal with, but hopefully this will help.

1. Go to your start menu's startup folder.
    (this is normally `C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\`)
2. Right click on ClickFix.lnk (the shortcut that opens clickfix)
3. Navigate to the "Compatibility" tab, and check "Run this program as an administrator". 

Hopefully, now, clickfix should start with administrator privileges. 

Unfortunately, that's pretty much all I can recommend to solve this issue, so I'll close this thread.
