### ISSUE TITLE
Left clicks not registering after bringing certain windows into focus

### ISSUE THREAD

**Issue by 20excal07** [CemraJC/clickfix#25]
I can consistently reproduce this issue with the Task Scheduler window (or any part of `mmc.exe`), but I've had this happen on other occasions as well with other things, like Regedit.

I only have ClickFix set to tame my left clicks.

To reproduce it:
1) Open `mmc.exe` (or Task Scheduler, etc.)
2) Once the window appears, try to click anywhere out of it - nothing will register.
3) To regain control, right-click anywhere outside of the window - the left clicks will work again after.

Hope you can patch this little bit of inconvenience. c:

**Comment by RikisX** [comment]
Try running clickfix.exe as administrator. It should help.

**Comment by 20excal07** [comment]
> Try running clickfix.exe as administrator. It should help.

Welp, that works.
