### ISSUE TITLE
Virus Total 22/62 

### ISSUE THREAD

**Issue by Fogony** [CemraJC/clickfix#26]
I'm afraid to catch a virus on my PC. Virustotal says it's a trojan, can you do something about it?

**Comment by CemraJC** [comment]
The software is safe, but unfortunately it uses similar code to other pieces of software that aren't.

AutoHotKey is a trusted scripting platform so far. If you're worried about viruses, I would suggest you download the source code, review it, and then compile the software yourself - that way you can be (mostly) sure of what you're running!
