### ISSUE TITLE
Not using compression may get rid of antivirus false positives

### ISSUE THREAD

**Issue by realdomdom** [CemraJC/clickfix#27]
#1 #8 #26 #24 
@CemraJC @Fogony @rigin @NNpranav
[https://www.hybrid-analysis.com/sample/91915970ec2b97673a351f52628d404b505ced5bab449c67d85c9745f5f04c7d/61c015f65c473919a823c5a9](https://www.hybrid-analysis.com/sample/91915970ec2b97673a351f52628d404b505ced5bab449c67d85c9745f5f04c7d/61c015f65c473919a823c5a9) might be a possible indication of you using a compromised version of the MPRESS compression program during your compilation of the AHK script.  
The download from [https://mpress.soft32.com](https://mpress.soft32.com/) may be malicious. 
If you don't do already, use this one [https://www.autohotkey.com/mpress/mpress_web.htm](https://www.autohotkey.com/mpress/mpress_web.htm) instead, use the UPX compression program or don't use any compression at all. 

If i'm mistaken then please ignore this.

I have compiled the script with no compression and uploaded it to virustotal, which significantly reduced the number of false positives [https://www.virustotal.com/gui/file/059d997835d4507156bc6ad26de10892dbe7b2353ed18f02ca27b1ec0b67f46f/detection](https://www.virustotal.com/gui/file/059d997835d4507156bc6ad26de10892dbe7b2353ed18f02ca27b1ec0b67f46f/detection).
![image](https://user-images.githubusercontent.com/8751735/170864666-80ba71f5-99fa-4878-8a14-d74635a645b9.png)

**Comment by CemraJC** [comment]
Thanks for posting your findings - I'm going to go through and compile a latest version now :+1:

**Comment by CemraJC** [comment]
I've released a new version with no compression. Hopefully this resolves the issue - otherwise, you may need to add an antivirus exception for Clickfix.exe
