### ISSUE TITLE
Conflict with AutoHotkey

### ISSUE THREAD

**Issue by SeriousBuggie** [CemraJC/clickfix#28]
I try use ClickFix for left mouse button, but it fully block any click to it.
I already run AHK 1.33.10 (when ClickFix compiled with 1.33.09).
If I unload AHK with my script it start work.
So I think it just not compatible with AHK. Possible both try install same handlers.

If I run ahk file (via my AHK) issue still in place. I need unload something one for mouse able work.

**Comment by SeriousBuggie** [comment]
Solve it by merge my simple scripts with ClickFix.

At end ClickFix write 
`#If, true`
And code of my simple script.

**Comment by CemraJC** [comment]
Thanks for posting your solution!
