### ISSUE TITLE
Feature Request For scrollFix 

### ISSUE THREAD

**Issue by Nygma297** [CemraJC/clickfix#3]
Could You add a feature for fixing scroll button? My scroll button is malfunctioning i.e. it scrolls up and down simultaneously when the button is scrolled down or up. Thus causing scroll malfunction. If you could please add a feature that would be awesome.

**Comment by CemraJC** [comment]
Sorry for the long delay.

At the moment, I'm fairly busy with other things, however when I have time, I will look into writing a feature that debounces scrolling as well. If you have any more suggestions, let me know :smile:

**Comment by MacgyverJohnson** [comment]
Hello there @CemraJC ,
Thanks for the amazing nifty utility, I would like debouncing for middle mouse as well...
Best Regards

**Comment by MacgyverJohnson** [comment]
Hello there @CemraJC 
Totally love this awesome app....
Would u please consider implementing keyboard/mouse shortcut for temporarily disabling clickfix....When clickfix is enabled...double click does not work but it does its job...tames single click....
TIA
Yours Truly

**Comment by CemraJC** [comment]
@MacgyverJohnson Thank you for your suggestion! Please see issue #4 for further comments.

**Comment by CemraJC** [comment]
@Nygma297 I have had a look into the functionality for debouncing scroll actions, and unfortunately, with the existing script, it would not be an easy job to implement a "scrollfix". 

You're more than welcome to fork this repository and try it yourself (I can answer any questions to get you up to speed if need be) but I cannot justify spending the time on this feature myself.

Sorry for this outcome, especially after having waited so long for a resolution  - I do appreciate your suggestion, please do not hesitate to contact me if anything else comes up.
