### ISSUE TITLE
Crash to desktop due to conflict with game anti-cheat

### ISSUE THREAD

**Issue by alufena** [CemraJC/clickfix#31]
If I play with ClickFix in the background and with the specific game, Quake Champions from bethesda, crashes to desktop :( I tried starting without it and apparently that was it

**Comment by CemraJC** [comment]
Yes - Clickfix takes control of your mouse to regulate the clicks, which is a trick that some cheating software uses for auto-aim/auto-shoot. Unfortunately, there's nothing we can do to prevent anti-cheat from flagging the software.
