### ISSUE TITLE
Why Do I Have To Keep Restarting the program???????????

### ISSUE THREAD

**Issue by tylerpak18** [CemraJC/clickfix#34]
Bro, can you make the program run only once so my clicks won't register twice because when I first ran it, it works for a couple seconds then returns to double click normally. It's irritating me that I have to right click and restart in order to make it active again. Please fix it.

**Comment by CemraJC** [comment]
Couldn't reproduce this issue. Can I suggest downloading the source script & autohotkey, then running it from the script instead of using the .exe?
