### ISSUE TITLE
Blocked by McAfee

### ISSUE THREAD

**Issue by Val8521** [CemraJC/clickfix#37]
After the initial launch, I received a security alert message from McAfee Endpoint Security, saying "Threat Type: Real Protect-PENG4!22890BB6DDF8". Then the program was terminated and ClickFix.exe was deleted.
Is there anything I can do?

**Comment by CemraJC** [comment]
Unfortunately not - perhaps you could try to run the script from AHK directly? The way the program works is to take over the mouse handler, so some virus scanners see that as a risk.
