### ISSUE TITLE
Feature Request: add forward and back mouse buttons too

### ISSUE THREAD

**Issue by wesamco** [CemraJC/clickfix#5]
Hey, cool project thanks for creating and open sourcing it. 
I believe it even can rescue mouses from the bin and have a positive environmental impact :) 
this should be simple, sorry I don't have AHK scripting experience, I would have submitted a PR.

**Comment by CemraJC** [comment]
Glad you like it!
Is your mouse having issues with forward/back buttons? That's a bit odd. I don't personally use the forward and back buttons, but nonetheless, I think it's a good idea to include them in the program.

I've put it on my long-term todo list. At this stage, I can't promise anything, but hopefully I'll have the time to implement this after Christmas.

Of course, if you wanted to learn a fun skill like AHK, I would definitely appreciate the contribution to the project.

Kind regards, Jason.

**Comment by wesamco** [comment]
@CemraJC trying AHK script was not fun.. #6

**Comment by CemraJC** [comment]
Hm, ok - I concurr. For what it does, it definitely could have been designed better. 
I'm sorry for what you went through here, but do know that I very much appreciate your contribution 😄
